# Default config for base Docker Image, override via DockerVolume
server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://${INSTANCE_URL}:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en-US
    #cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/templates
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    ogc_schemas_location: /schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Geoscience Australia PID
        description: This service is powered by pygeoapi, an API to geospatial data
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/geopython/pygeoapi
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: pygeoapi Development Team
        url: https://pygeoapi.io
    contact:
        name: Kralidis, Tom
        position: Lead Dev
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Canada
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Hours of Service
        instructions: During hours of service.  Off on weekends.
        role: pointOfContact

resources:
    fs:
        type: collection
        title: Field Site
        description: Geoscience Australia - Field Site data for PID landing page
        keywords:
            - fieldsite
            - Geoscience
            - Australia
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.ga.gov.au/
              hreflang: en-US
        extents:
            spatial:
                bbox: [105,-45,160,-5] #world -180,-90,180,90
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2023-11-11
                end: null  #or empty (either means open ended)
        providers:
            - type: feature
              name: OracleDB
              data:
                  host: ${DB_HOST}
                  port: 1521
                  service_name: ${DB_SERVICE}
                  user: ${DB_USER}
                  password: "${DB_PWD}"
                  search_path: ["PUB_DATA", "$user"]
              id_field: ENO
              table: PUB_DATA.PIDUSER_VIEW_FIELDSITE
              title_field: ENO
              geom_field: GEOM
              url_field: ENO

    hello-world:
        type: process
        processor:
            name: HelloWorld
